# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    core.extension:
        class: AppBundle\Twig\CoreExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }

    note.listener:
        class: AppBundle\Listener\NoteListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postFlush }